version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/qrt-nightwatch/ # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:latest # ...with this image as the primary container;
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: update libraries
          command: apt-get install libnss3 libgconf-2-4
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-nightwatch
          command: npm install nightwatch --save-dev
      - run:
          name: install-npm-selenium-server
          command: npm install selenium-server
      - run:
          name: install-npm-chromedriver
          command: npm install chromedriver --save-dev
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: tests_output/*.xml
          prefix: tests
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: tests_output/*.xml